---
title: "Testing Royle 2008 CJS State-space"
author: "Michelle DePrenger-Levin"
date: "2023-09-08"
output: html_document
---

```{r}
library(rjags)
library(dplyr)
library(tidyr)
library(ggplot2)
library(R2jags) ## jags
library(R2WinBUGS)

```


Simulate state-space model via Schaub and Kery 2022    
```{r}
# Choose constants
nyear <- 25 # Number of years
N1 <- 30 # Initial abundance
mu.lam <- 1.02 # Mean of the distribution of lambda
sig2.lam <- 0.02 # Variance of the distribution of lambda

# Simulate true system state
N <- numeric(nyear)
N[1] <- N1 # Set initial abundance
set.seed(1) # Initialize the RNGs
lambda <- rnorm(nyear-1, mu.lam, sqrt(sig2.lam)) # Draw random lambda

for (t in 1:(nyear-1)){
  N[t+1] <- rpois(1, lambda[t] * N[t]) # Propagate population size forwards
}
plot(N, type = "l")

# Simulate observations
y <- rpois(nyear, N) # Observation error is now Poisson noise, might over and under-count

# Data bundle
jags.data <- list(y=y, T=length(y))


# Write JAGS model file
cat(file = "model6.txt", "
  model {
  
  # Priors and linear models
  mu.lam ~ dunif(0, 10) # Prior for mean growth rate
  sig.lam ~ dunif(0, 2) # Prior for sd of growth rate
  sig2.lam <- pow(sig.lam, 2)
  tau.lam <- pow(sig.lam, -2)
  
  # Likelihood
  # Model for the initial population size: uniform priors
  N[1] ~ dunif(0, 500)
  
  # Process model over time: our model of population dynamics
  for (t in 1:(T-1)){
    lambda[t] ~ dnorm(mu.lam, tau.lam)
    N[t+1] ~ dpois(N[t] * lambda[t])
  }
  # Observation process
  for (t in 1:T){
    y[t] ~ dpois(N[t])
  }
  }
")
# Initial values
inits <- function(){list(sig.lam=runif(1, 0, 1), mu.lam=runif(1, 0.1, 2),
                         N=round(runif(nyear, 20, 40)))}
# Parameters monitored
parameters <- c("mu.lam", "sig2.lam", "sig.lam", "N")
# MCMC settings
ni <- 20000; nb <- 10000; nc <- 3; nt <- 10; na <- 1000
# Call JAGS from R (ART <1 min), check convergence and summarize posteriors
out9 <- jags(jags.data, inits, parameters, "model6.txt", n.iter=ni, n.burnin=nb, n.chains=nc,
             n.thin=nt)  # n.adapt=na, 
             # parallel=TRUE)
traceplot(out9) # Not shown

print(out9, 3) # Not shown

plot(N)
lines(N)
points(out9$BUGSoutput$mean$N, col = "red")
lines(out9$BUGSoutput$mean$N, col = "red")
points(out9$BUGSoutput$median$N, col = "blue")
lines(out9$BUGSoutput$mean$N, col = "blue")

boxplot(lambda, col = 'red', alpha = 0.5)
boxplot(out9$BUGSoutput$sims.list$mu.lam)

out9$


```

Zero-inflated Poisson (ZIP)  
```{r}
## Simulate data
# Choose constants in simulation
nbrood <- 1000 # Number of broods with young counted, i.e. number of fruit
theta <- 0.7 # Success probability in Bernoulli process; any seed produced? 
brood.mean <- 1.5 # Average brood size in conditional Poisson process; number seed per fruit
sd.brood <- 0.3 # Overdispersion in conditional Poisson process; more zeros
# Simulate Bernoulli process dividing broods in failures and 'potential successes'
set.seed(46)
z <- rbinom(nbrood, 1, theta) # z = 1 means 'potential success'
# Draw conditional Poisson random numbers with overdispersion
expNyoung <- z * exp(log(brood.mean) + rnorm(nbrood, 0, sd.brood))
Cx <- rpois(nbrood, expNyoung)
table(Cx)
# Data bundle
jags.data <- list(C=Cx, nbrood=nbrood)


# Write JAGS model file
cat(file="model9.txt", "
  model {
  # Priors and linear models
  theta ~ dunif(0, 1) # Success probabiliy in Bernoulli process
  rho ~ dunif(0, 5) # Mean brood size in conditional Poisson
  tau.rho <- pow(sd.rho, -2)
  sd.rho ~ dunif(0, 3) # Overdispersion in conditional Poisson
  
  # Likelihood
  # Note this is a zero-inflated Poisson log-normal GLMM .... cool !
  for (i in 1:nbrood){
    z[i] ~ dbern(theta) # Zero-inflation process; yes or no
    C[i] ~ dpois(z[i] * cond.pois.mean[i]) # Conditional Poisson
    log(cond.pois.mean[i]) <- log.condmean[i]
    log.condmean[i] ~ dnorm(log(rho), tau.rho) # Overdispersion
  }
}
")
# Initial values
inits <- function(){list(z=rep(1, nbrood), rho=runif(1, 0.5, 2.5))}
# Parameters monitored
parameters <- c("theta", "rho", "sd.rho")
# MCMC settings
ni <- 110000; nb <- 10000; nc <- 3; nt <- 100; na <- 1000
# Call JAGS from R (ART 6 min) and check convergence
out12 <- jags(jags.data, inits, parameters, "model9.txt", n.iter=ni, n.burnin=nb, n.chains=nc,
              n.thin=nt) #, n.adapt=na, parallel=TRUE)
# traceplot(out12) # Not shown
print(out12, 3)
```

```{r}
# Choose constants in simulation
nbrood <- 1000 # Number of broods with young counted
brood.mean <- 1.5 # Average brood size
sd.brood <- 0.3 # log-linear brood random effect
# Draw Poisson random numbers
set.seed(24)
expNyoung <- exp(log(brood.mean) + rnorm(nbrood, 0, sd.brood))
C <- rpois(nbrood, expNyoung)
table(C)
## partial zero-truncation
# Create a variant of the data with partial zero truncation
set.seed(68)
C1 <- C # Copy data set
table(C1) # Remind ourselves of the actual data
prop.uncertain <- 0.6 # Proportion of zeros dropped
zeros <- which(C1==0)
toss <- zeros[rbinom(n=length(zeros), size=1, prob=prop.uncertain) == 1]
C1 <- C1[-toss] # Toss out some of the zeros
table(C1) # Frequency dist. of new brood size data
# Make another copy of C1 data and kick out remaining zeroes as well
C2 <- C1[C1 > 0] # Make a copy and toss out remaining zeroes
# Data bundle
jags.data <- list(C1=C1, C2=C2, nC1=length(C1), nC2=length(C2))

# Write JAGS model file
cat(file="model10.txt", "
model {
  # Priors and linear models
  rho1 ~ dunif(0, 3) # Expected brood size in model 1
  rho2 ~ dunif(0, 3) # Expected brood size in model 2
  # Likelihoods
  # Model 1: Standard Poisson GLM
  for (i in 1:nC1){
    C1[i] ~ dpois(rho1)
  }
  # Model 2: Poisson GLM with response truncated at one (i.e., no zeroes)
  for (i in 1:nC2){
    C2[i] ~ dpois(rho2)T(1,)   ## What is T(1,) doing? 
  }
}
")

```


Right-censoring: X or more fruit and an indicator of which individuals missed some fruit (too early, fruit dropped, etc.)   
```{r}
# Simulate right-censored Poisson observations
set.seed(1)
C3 <- C # Make another copy of the data set
sum(C3 >= 2) # How many broods 2 or greater ? -- 439
large.broods <- which(C3>=2) # Index them
censored.broods <- sample(large.broods, 300) # Randomly select 300
C3[censored.broods] <- C3[censored.broods] - 1 # Censor these 300
mean(C) # True mean
mean(C3) # Mean of C3 biased low
C4 <- C3 # Make another copy
C4[censored.broods] <- NA # Censored are NA'd out
d <- as.numeric(is.na(C4)) # Binary censoring indicator
cens.threshold <- C3
cens.threshold[d==0] <- C3[d==0] + 0.1


# Data bundle
jags.data <- list(C4=C4, d=d, cens.threshold=cens.threshold, nbrood=nbrood)
str(jags.data)

# Write JAGS model file
cat(file="model11.txt", "
model {
# Prior
rho ~ dunif(0, 5)
# Likelihood
for (i in 1:nbrood){
C4[i] ~ dpois(rho)
prob.censored[i] <- step(C4[i] - cens.threshold[i])
d[i] ~ dbern(prob.censored[i])
}
}
")
# Initial values
C4st <- rep(NA, nbrood)
C4st[is.na(C4)] <- C3[is.na(C4)]
inits <- function() list(rho=runif(1), C4=C4st)
# Parameters monitored
parameters <- c("rho", "C4", "prob.censored")
# MCMC settings
ni <- 2000; nb <- 1000; nc <- 3; nt <- 2; na <- 1000
# Call JAGS from R (ART <1 min), check convergence and summarize posteriors
out14 <- jags(jags.data, inits, parameters, "model11.txt", n.iter=ni, n.burnin=nb, n.chains=nc,
              n.thin=nt) #, n.adapt=na, parallel=TRUE)
# traceplot(out14) # Not shown
print(out14, 3)
```


Read in annual data, correct for typos
```{r}
# currentyr <- as.numeric(format(as.Date(Sys.Date(),format="%Y-%m-%d"), "%Y"))
currentyr <- 2022

##To change if someone other than Michelle is running code
userpath <- "C:/Users/DePrengm/"

rawdatapath <- paste(userpath, "Denver Botanic Gardens/Conservation - General/AllProjectsBySpecies/Astragalus-microcymbus/Astragalus-microcymbus_Data/", currentyr, "_Astragalus-microcymbus_RawData.csv", collapse = '', sep = '')

asmi.raw <- read.csv(rawdatapath, na.strings = "na")

# need to remove all plot 89, site 1 in 2020 and beyond
asmi.raw <- asmi.raw[!(asmi.raw$AsMi_plot_id == 89 & asmi.raw$year > 2019),]


# For the path and start of the name of each file
savepath <- paste(userpath, "Denver Botanic Gardens/Conservation - General/AllProjectsBySpecies/Astragalus-microcymbus/Astragalus-microcymbus_AnnualReports/", currentyr, "_Astragalus-microcymbus_AnnualReport/", collapse = '', sep = '')


asmi.raw$length[is.na(asmi.raw$length)] <- 0

# For plots that didn't start in 1995 !!! All new plants are listed as seedlings in 2014 and none should
table(asmi.raw$AsMi_plot_id[asmi.raw$AsMi_site_id==1], 
      asmi.raw$status[asmi.raw$AsMi_site_id==1], 
      asmi.raw$year[asmi.raw$AsMi_site_id==1])

table(asmi.raw$AsMi_plot_id[asmi.raw$AsMi_site_id==2], 
      asmi.raw$status[asmi.raw$AsMi_site_id==2], 
      asmi.raw$year[asmi.raw$AsMi_site_id==2])

# Site 26 had two plots added later; Plots 238 and 300 were added in 1996 with no seedlings! good!;  plot 598 was added in 2004, no seedlings, good!  
table(asmi.raw$AsMi_plot_id[asmi.raw$AsMi_plot_id %in% c(238,300,598)], 
      asmi.raw$status[asmi.raw$AsMi_plot_id %in% c(238,300,598)],
      asmi.raw$year[asmi.raw$AsMi_plot_id %in% c(238,300,598)])

# Need to change all the seedling in 2014 for sites 1 and 2 to appropriate vegetative or reproductive 
asmi.raw$status[asmi.raw$AsMi_site_id<3 & asmi.raw$year == 2014 & asmi.raw$flower == 0] <- "vegetative"
asmi.raw$status[asmi.raw$AsMi_site_id<3 & asmi.raw$year == 2014 & asmi.raw$flower == 1] <- "reproductive"

# No longer adding climate data to the database
asmi.raw <- asmi.raw[,grep(paste(c("Temp","Rain","Snow","Aug.Jul"),collapse="|"), names(asmi.raw),
                           value = TRUE, invert = TRUE)]

table(asmi.raw$year, asmi.raw$AsMi_site_id)
table(asmi.raw$year, asmi.raw$AsMi_plot_id)
table(asmi.raw$Browsing...Status)
asmi.raw$Browsing...Status[asmi.raw$Browsing...Status == "mammal" ] <- "Mammal"
asmi.raw[asmi.raw$Browsing...Status ==""& !is.na(asmi.raw$Browsing...Status),]
asmi.raw[is.na(asmi.raw$AsMi_data_id),]
asmi.raw <- asmi.raw[!is.na(asmi.raw$AsMi_data_id),] # remove any rows with NA for data_id

# Which plot # go with which site
plotsXsite <- as.data.frame(table(asmi.raw$AsMi_plot_id,asmi.raw$AsMi_site_id))
plotsXsite[plotsXsite$Freq > 0,]

# one blank row at the end of the csv download, gone by 2021
asmi.raw[asmi.raw$status == "",]
# asmi.raw <- asmi.raw[asmi.raw$status != "",]
asmi.raw$status <- factor(asmi.raw$status)
table(asmi.raw$status)

#reset factors of browsing to eliminate " "
# asmi.raw$Browsing...Status[asmi.raw$Browsing...Status == "mammal"] <- "Mammal"
asmi.raw$Browsing...Status <- factor(asmi.raw$Browsing...Status)

#reset factors for fence
asmi.raw$fence <- factor(asmi.raw$fence)
table(asmi.raw$fence)

asmi.raw[asmi.raw$length>90 & !is.na(asmi.raw$length),] 
asmi.raw$length[asmi.raw$length == 921] <- 21

# If there are fruit, it flowered and needs to be reproductive, not vegetative
asmi.raw[asmi.raw$status=="vegetative" & asmi.raw$fruit>0,] # 5 times in 2020
wrongAsMidataid <- asmi.raw$AsMi_data_id[asmi.raw$status=="vegetative" & asmi.raw$fruit>0]
asmi.raw$flower[asmi.raw$AsMi_data_id %in% wrongAsMidataid] <- 1
asmi.raw$status[asmi.raw$AsMi_data_id %in% wrongAsMidataid] <- "reproductive"
asmi.raw[asmi.raw$AsMi_data_id %in% wrongAsMidataid,]

# Years of study in the abstract
length(1995:currentyr)


```


```{r}
# Survival of each individual, assuming perfect detection
# x = observation process, zero if not seen, NA if before first year
# first = the first year that an individual was observed

# the first occurrence always needs to be 1
## Change to fill in complete year 2014:2022 for site 1 & 2, 1995:2022 for others except the two plots
asmi.SSM <- asmi.raw %>%
  group_by(AsMi_site_id, AsMi_plot_id, AsMi_tag_id) %>%
  complete(year = full_seq(1995:2022, 1)) %>%
  fill(length) %>%
  summarise(x = if_else(length > 0, 1, 0),
            year = year,
            length = length)

asmi.raw[asmi.raw$length ==0,]
asmi.SSM %>%
  filter(is.na(length)) %>%
  print(n=100)

asmi.SSM %>%
  group_by(AsMi_tag_id) %>%
  summarise(n())

# asmi.SSM %>%
#   print(n = 100)



## The first year a plant was seen from the first year the site was established
first <- asmi.raw %>%
  group_by(AsMi_site_id, AsMi_plot_id, AsMi_tag_id) %>%
  dplyr::summarise(minYr = min(year)) %>%
  # mutate(first = ifelse(AsMi_site_id < 5, minYr - 2013, minYr - 1994))
  mutate(first = case_when(AsMi_site_id %in% c(1,2) ~ minYr - 2013,
                           AsMi_site_id %in% c(5,15,19,26) ~ minYr - 1994,
                           AsMi_plot_id == 238 ~ minYr - 1995,
                           AsMi_plot_id == 598 ~ minYr - 2003))

first.temp <- asmi.raw %>%
  group_by(AsMi_site_id, AsMi_plot_id, AsMi_tag_id) %>%
  dplyr::summarise(minYr = min(year)) %>%
  mutate(first = minYr - 1994)

### Have an individual covariate, can use fenced as covariate
fence <- asmi.raw %>%
  group_by(AsMi_site_id, AsMi_plot_id, AsMi_tag_id) %>%
  dplyr::summarise(fence = unique(fence))

numtags <- asmi.raw %>%
  group_by(AsMi_site_id, AsMi_plot_id) %>%
  summarize(ntags = n_distinct(AsMi_tag_id))

sum(numtags$ntags) ## 4099 individuals

jagsdata <- list(x = matrix(asmi.SSM$x, byrow = TRUE, 
                            ncol = length(1995:2022), nrow = sum(numtags$ntags)),
                 first = first.temp$first,
                 nind = sum(numtags$ntags), nyear = length(1995:2022), 
                 covariate = as.numeric(as.factor(fence$fence))-1)


```

```{r}
StateSpace_CJS <- 
  paste("

model {
### Note: covariate is a vector of length nind
for(j in 1:(nyear-2)){
  p[j]~dunif(0,1)
  lp[j]<-log(p[j]/(1-p[j]))
  phi[j]~dunif(0,1)
  lphi[j]<-log(phi[j]/(1-phi[j]))
}
  
p[nyear-1]~dunif(0,1)
lp[nyear-1] <- log(p[nyear-1]/(1-p[nyear-1]))
lphi[nyear-1] <- 0
sigma.phi~dunif(0,10)
sigma.p~dunif(0,10)
tauphi <- 1/(sigma.phi*sigma.phi)
taup<-1/(sigma.p*sigma.p)
coef~dnorm(0.0,0.01)

for(i in 1:nind){
  eta[i]~dnorm(0,taup)
  delta[i]~dnorm(0,tauphi)
  for(t in 1:(nyear-1)){
    logit(p[i,t]) <- lp[t] + eta[i]
    logit(phi[i,t])<- lphi[t] + delta[i] + coef*covariate[i]
  }
}

for(i in 1:nind){
  z[i,first[i]]~dbern(1)
  for(j in (first[i]+1):nyear){
    mu2[i,j]<-phi[i,j-1]*z[i,j-1]
    z[i,j]~dbern(mu2[i,j])
    mu1[i,j]<-p[i,j-1]*z[i,j]
    x[i,j]~dbern(mu1[i,j])
  }
}
}")
writeLines(StateSpace_CJS, "StateSpace_CJS.jags")

```
```{r}
## parameters monitored
parameters <- c("mu1","mu2","z","x","p","pl","phi","lphi")
# MCMC settings
ni <- 10000
nt <- 6
nb <- 5000
nc <- 3
# call JAGS from R
res1 <- jags(jagsdata, inits = NULL, parameters, 
            "StateSpace_CJS.jags", n.chains = nc, n.thin = nt, 
            n.iter = ni, n.burnin = nb,
            working.directory = getwd()) 

save(res1, file = paste("./Rdatas/ExistShape",Sys.Date(),".Rdata", sep=""))

```



Single season   
```{r}

```

