---
title: "Robust Design AsMi"
author: "Michelle DePrenger-Levin"
date: "2023-11-30"
output: ''
---

Libraries and data
```{r}
rm(list=ls())
library(dplyr)
library(tidyr)
library(ggplot2)
library(RMark)

load("C:/Users/deprengm/OneDrive - Denver Botanic Gardens/P drive/hackathon/GitPVA/datasets/Robust3years.Rdata")

load("C:/Users/deprengm/OneDrive - Denver Botanic Gardens/P drive/hackathon/GitPVA/datasets/plotdf.Rdata")
load("C:/Users/deprengm/OneDrive - Denver Botanic Gardens/P drive/hackathon/GitPVA/datasets/sitedf.Rdata")

```



## Robust example - not multi-state   
inp created in CJS_SeedlingSurvival.Rmd, poor name, changed focus
```{r}


asmiRDPlot.inp <- convert.inp("C:/Users/deprengm/OneDrive - Denver Botanic Gardens/P drive/hackathon/GitPVA/datasets/Robust3yearsPlot.inp",
                          group.df = plotdf,
                          covariates = NULL,
                          use.comments = FALSE)


```


Format data of all years
```{r}
asmi.raw <- asmi.raw3

## Just add "." for all the ones that we're measured
# assign group at first encounter, age 0 if 'seedling' or vegetative, older if reproductive. 
CJS_asmi <- asmi.raw %>%
  filter(!(AsMi_tag_id %in% c(1177,1171,2746,3903))) %>%
  filter(!is.na(year)) %>%  
  dplyr::select(c(AsMi_tag_id:status,AsMi_plot_id:fence)) %>%
  group_by(AsMi_tag_id) %>%
  filter(any(length > 0)) %>%
  mutate(first.cap.stage = status[which.min(year[length>0])]) %>%
  ungroup() %>%
  mutate(Obs = case_when(length > 0 ~ 1, 
                         length == 0 ~ 0,
                         is.na(length) ~ 0)) %>%
  arrange(year) %>%
  mutate(Obs = as.character(Obs)) %>%
  pivot_wider(names_from = year, values_from = Obs, values_fill = "0", names_prefix = "Year", 
              id_cols = c(AsMi_tag_id,AsMi_site_id,AsMi_plot_id, fence,first.cap.stage)) %>%
  mutate(Year1995 = case_when((AsMi_plot_id %in% c(300,238,598) | AsMi_site_id %in% c(1,2)) ~ ".",
                              TRUE ~ Year1995),
         Year1996 = case_when((AsMi_plot_id %in% c(598) | AsMi_site_id %in% c(1,2)) ~ ".",
                              TRUE ~ Year1996),
         Year1997 = case_when((AsMi_plot_id %in% c(598) | AsMi_site_id %in% c(1,2)) ~ ".",
                              TRUE ~ Year1997),
         Year1998 = case_when((AsMi_plot_id %in% c(598) | AsMi_site_id %in% c(1,2)) ~ ".",
                              TRUE ~ Year1998),
         Year1999 = case_when((AsMi_plot_id %in% c(598) | AsMi_site_id %in% c(1,2)) ~ ".",
                              TRUE ~ Year1999),
         Year2000 = case_when((AsMi_plot_id %in% c(598) | AsMi_site_id %in% c(1,2)) ~ ".",
                              TRUE ~ Year2000),
         Year2001 = case_when((AsMi_plot_id %in% c(598) | AsMi_site_id %in% c(1,2)) ~ ".",
                              TRUE ~ Year2001),
         Year2002 = case_when((AsMi_plot_id %in% c(598) | AsMi_site_id %in% c(1,2)) ~ ".",
                              TRUE ~ Year2002),
         Year2003 = case_when((AsMi_plot_id %in% c(598) | AsMi_site_id %in% c(1,2)) ~ ".",
                              TRUE ~ Year2003),
         Year2004 = case_when(AsMi_site_id %in% c(1,2) ~ ".",
                              TRUE ~ Year2004),
         Year2005 = case_when(AsMi_site_id %in% c(1,2) ~ ".",
                              TRUE ~ Year2005),
         Year2006 = case_when(AsMi_site_id %in% c(1,2) ~ ".",
                              TRUE ~ Year2006),
         Year2007 = case_when(AsMi_site_id %in% c(1,2) ~ ".",
                              TRUE ~ Year2007),
         Year2008 = case_when(AsMi_site_id %in% c(1,2) ~ ".",
                              TRUE ~ Year2008),
         Year2009 = case_when(AsMi_site_id %in% c(1,2) ~ ".",
                              TRUE ~ Year2009),
         Year2010 = case_when(AsMi_site_id %in% c(1,2) ~ ".",
                              TRUE ~ Year2010),
         Year2011 = case_when(AsMi_site_id %in% c(1,2) ~ ".",
                              TRUE ~ Year2011),
         Year2012 = case_when(AsMi_site_id %in% c(1,2) ~ ".",
                              TRUE ~ Year2012),
         Year2013 = case_when(AsMi_site_id %in% c(1,2) ~ ".",
                              TRUE ~ Year2013)) %>%
  unite(ch, Year1995:Year2022, sep ="") %>%
  mutate(Tag = as.factor(AsMi_tag_id),
         Site = as.factor(AsMi_site_id),
         Plot = as.factor(AsMi_plot_id))

dmPlot <- model.matrix(~ -1 + Plot, CJS_asmi)  
dmSite <- model.matrix(~ -1 + Site, CJS_asmi)
finalplot <- dimnames(dmPlot)[[2]][length(dimnames(dmPlot)[[2]])]

## By Plot
CJS_asmi %>%
  dplyr::select(ch) %>%
  bind_cols(dmPlot) %>%
  mutate(Plot799 = paste(Plot799, ";", sep = "")) %>%
  write.table(file = "C:/Users/deprengm/OneDrive - Denver Botanic Gardens/P drive/hackathon/GitPVA/datasets/CJS_asmi_mark.inp", sep = " ", 
              col.names = FALSE, row.names = FALSE)

## By Site
CJS_asmi %>%
  dplyr::select(ch) %>%
  bind_cols(dmSite) %>%
  mutate(Site26 = paste(Site26, ";", sep = "")) %>%
  write.table(file = "C:/Users/deprengm/OneDrive - Denver Botanic Gardens/P drive/hackathon/GitPVA/datasets/CJS_asmi_mark_site.inp", sep = " ", 
              col.names = FALSE, row.names = FALSE)

fields <- CJS_asmi %>%
  dplyr::select(ch) %>%
  bind_cols(dmSite) %>%
  bind_cols(dmPlot) %>%
  colnames()

plotdf <- CJS_asmi %>%
  distinct(Site,Plot)

sitedf <- CJS_asmi %>%
  distinct(Site)

```



Mark-recapture by plot    
```{r}

## Convert for MARK  
asmiRDPlot.inp <- convert.inp("C:/Users/deprengm/OneDrive - Denver Botanic Gardens/P drive/hackathon/GitPVA/datasets/Robust3yearsPlot.inp", 
                        group.df = plotdf,
                        covariates = NULL,
                        use.comments = FALSE)

asmiRDSite.inp <- convert.inp("C:/Users/deprengm/OneDrive - Denver Botanic Gardens/P drive/hackathon/GitPVA/datasets/Robust3yearsSite.inp", 
                        group.df = sitedf,
                        covariates = NULL,
                        use.comments = FALSE)
```


```{r}

run.robust <- function(){
  ## 3 primary sessions with secondary sessions all of length 10 ("." for missing surveys)
  time.interva
}

```

